export const presetRegistry = [
    {
  id: 1001,
  providerType: "generic",
  category: "Generic",
  macroCode: null,
  displayName: "Balanced",
  hiddenInstruction: "Balance clarity, structure, and token efficiency.",
  mvpCandidate: true,
  notes: "Default optimization mode",
  userEditable: false,
},
{
  id: 1002,
  providerType: "generic",
  category: "Generic",
  macroCode: "tldr",
  displayName: "Concise",
  hiddenInstruction: "Maximum token reduction with minimal output.",
  mvpCandidate: true,
  notes: "High compression mode",
  userEditable: false,
},
{
  id: 1003,
  providerType: "generic",
  category: "Generic",
  macroCode: null,
  displayName: "Creative",
  hiddenInstruction: "Optimize for creative and open-ended tasks.",
  mvpCandidate: true,
  notes: "Creative mode",
  userEditable: false,
},
{
  id: 1004,
  providerType: "generic",
  category: "Generic",
  macroCode: "to the point",
  displayName: "Precise",
  hiddenInstruction: "Prioritize technical accuracy and detailed specifications.",
  mvpCandidate: true,
  notes: "Precision mode",
  userEditable: false,
},
{
  id: 1005,
  providerType: "generic",
  category: "Generic",
  macroCode: "human tone",
  displayName: "Conversational",
  hiddenInstruction: "Use a natural, friendly tone with clarity.",
  mvpCandidate: true,
  notes: "Friendly tone mode",
  userEditable: false,
},
  
    {
    id: 1,
    providerType: "chatgpt",
    category: "Communication",
    macroCode: "/human",
    displayName: "Humanize Tone",
    hiddenInstruction: "Use natural conversational language.",
    mvpCandidate: true,
    notes: "Natural response style",
    userEditable: true,
  },
  {
    id: 2,
    providerType: "chatgpt",
    category: "Communication",
    macroCode: "EL10",
    displayName: "Simplify all",
    hiddenInstruction: "Explain simply with minimal jargon.",
    mvpCandidate: true,
    notes: "Good for non-technical users",
    userEditable: true,
  },
  {
    id: 3,
    providerType: "chatgpt",
    category: "Reasoning",
    macroCode: "x10think",
    displayName: "Deep Analysis",
    hiddenInstruction: "Increase reasoning depth and evaluate trade-offs carefully.",
    mvpCandidate: true,
    notes: "High-value reasoning mode",
    userEditable: false,
  },
  {
    id: 4,
    providerType: "chatgpt",
    category: "Reasoning",
    macroCode: "killcritic",
    displayName: "Challenge my views",
    hiddenInstruction: "Challenge assumptions and identify weaknesses.",
    mvpCandidate: true,
    notes: "Useful for decision analysis",
    userEditable: true,
  },
  {
    id: 5,
    providerType: "chatgpt",
    category: "Reasoning",
    macroCode: "alt3",
    displayName: "Alternative options",
    hiddenInstruction: "Generate multiple distinct approaches.",
    mvpCandidate: true,
    notes: "Great for brainstorming",
    userEditable: true,
  },
  {
    id: 6,
    providerType: "chatgpt",
    category: "Reasoning",
    macroCode: "debate",
    displayName: "Different perspective",
    hiddenInstruction: "Present arguments from multiple sides.",
    mvpCandidate: false,
    notes: "Could overlap with pros/cons",
    userEditable: true,
  },
  {
    id: 7,
    providerType: "chatgpt",
    category: "Reasoning",
    macroCode: "devils advocate",
    displayName: "Skeptical twist",
    hiddenInstruction: "Actively question assumptions and edge cases.",
    mvpCandidate: false,
    notes: "Good for risk analysis",
    userEditable: true,
  },
  {
    id: 8,
    providerType: "chatgpt",
    category: "Workflow",
    macroCode: "step-by-step",
    displayName: "Step-by-Step",
    hiddenInstruction: "Respond using numbered steps.",
    mvpCandidate: true,
    notes: "Very common workflow",
    userEditable: false,
  },
  {
    id: 9,
    providerType: "chatgpt",
    category: "Formatting",
    macroCode: "no fluff",
    displayName: "Concise",
    hiddenInstruction: "Keep the response short and high signal.",
    mvpCandidate: true,
    notes: "Excellent for token savings",
    userEditable: false,
  },
  {
    id: 10,
    providerType: "chatgpt",
    category: "Communication",
    macroCode: "executive mode",
    displayName: "Ultimate summary",
    hiddenInstruction: "Prioritize strategic clarity and concise business language.",
    mvpCandidate: true,
    notes: "Strong enterprise fit",
    userEditable: true,
  },
  {
    id: 11,
    providerType: "chatgpt",
    category: "Reasoning",
    macroCode: "red team",
    displayName: "Show risks",
    hiddenInstruction: "Identify risks, vulnerabilities, and failure points.",
    mvpCandidate: true,
    notes: "Great for enterprise analysis",
    userEditable: true,
  },
  {
    id: 12,
    providerType: "chatgpt",
    category: "Reasoning",
    macroCode: "audit mode",
    displayName: "Audit Mode",
    hiddenInstruction: "Systematically inspect for inconsistencies and gaps.",
    mvpCandidate: true,
    notes: "Useful for technical/product reviews",
    userEditable: false,
  },
  {
    id: 13,
    providerType: "chatgpt",
    category: "Workflow",
    macroCode: "action plan",
    displayName: "Action Plan",
    hiddenInstruction: "Focus on actionable next steps.",
    mvpCandidate: true,
    notes: "Very high utility",
    userEditable: false,
  },
  {
    id: 14,
    providerType: "chatgpt",
    category: "Reasoning",
    macroCode: "fact-check",
    displayName: "Fact Check",
    hiddenInstruction: "Critically verify claims and assumptions.",
    mvpCandidate: true,
    notes: "Strong trust feature",
    userEditable: false,
  },
  {
    id: 15,
    providerType: "chatgpt",
    category: "Workflow",
    macroCode: "consultant mode",
    displayName: "Consult me",
    hiddenInstruction: "Use structured advisory-style communication.",
    mvpCandidate: true,
    notes: "Strong enterprise fit",
    userEditable: true,
  },
  {
    id: 16,
    providerType: "chatgpt",
    category: "Workflow",
    macroCode: "analyst mode",
    displayName: "Thesis mode",
    hiddenInstruction: "Use evidence-heavy analytical reasoning.",
    mvpCandidate: true,
    notes: "High-value enterprise preset",
    userEditable: true,
  },
  {
    id: 17,
    providerType: "chatgpt",
    category: "Formatting",
    macroCode: "json only",
    displayName: "JSON Output",
    hiddenInstruction: "Respond only in valid JSON format.",
    mvpCandidate: true,
    notes: "Important technical workflow",
    userEditable: false,
  },
  {
    id: 18,
    providerType: "chatgpt",
    category: "Formatting",
    macroCode: "table mode",
    displayName: "Table Format",
    hiddenInstruction: "Respond using structured tables.",
    mvpCandidate: true,
    notes: "Very useful comparison format",
    userEditable: false,
  },
];

export function listPresets({ providerType } = {}) {
  const activePresets = presetRegistry.filter(
    (preset) => preset.mvpCandidate
  );

  if (!providerType) {
    return activePresets.filter(
      (preset) => preset.providerType === "generic"
    );
  }

  const providerPresets = activePresets.filter(
    (preset) => preset.providerType === providerType
  );

  if (providerPresets.length > 0) {
    return providerPresets;
  }

  return activePresets.filter(
    (preset) => preset.providerType === "generic"
  );
}