export const RESPONSE_MODE_MAP = {
  default: {
    key: "default",
    displayName: "I'm scared to try",
    category: "General",
    communityMacro: "",
    instruction: "",
    mvpCandidate: "Yes",
  },
  humanize_tone: {
    key: "humanize_tone",
    displayName: "Humanize Tone",
    category: "Communication",
    communityMacro: "/human",
    instruction: "Use natural conversational language.",
    mvpCandidate: "Yes",
  },
  simplify_all: {
    key: "simplify_all",
    displayName: "Simplify all",
    category: "Communication",
    communityMacro: "EL10",
    instruction: "Explain simply with minimal jargon.",
    mvpCandidate: "Yes",
  },
  deep_analysis: {
    key: "deep_analysis",
    displayName: "Deep Analysis",
    category: "Reasoning",
    communityMacro: "x10think",
    instruction: "Increase reasoning depth and evaluate trade-offs carefully.",
    mvpCandidate: "Yes",
  },
  challenge_my_views: {
    key: "challenge_my_views",
    displayName: "Challenge my views",
    category: "Reasoning",
    communityMacro: "killcritic",
    instruction: "Challenge assumptions and identify weaknesses.",
    mvpCandidate: "Yes",
  },
  alternative_options: {
    key: "alternative_options",
    displayName: "Alternative options",
    category: "Reasoning",
    communityMacro: "alt3",
    instruction: "Generate multiple distinct approaches.",
    mvpCandidate: "Yes",
  },
  different_perspective: {
    key: "different_perspective",
    displayName: "Different perspective",
    category: "Reasoning",
    communityMacro: "debate",
    instruction: "Present arguments from multiple sides.",
    mvpCandidate: "Maybe",
  },
  skeptical_twist: {
    key: "skeptical_twist",
    displayName: "Skeptical twist",
    category: "Reasoning",
    communityMacro: "devils advocate",
    instruction: "Actively question assumptions and edge cases.",
    mvpCandidate: "Maybe",
  },
  step_by_step: {
    key: "step_by_step",
    displayName: "Step-by-Step",
    category: "Workflow",
    communityMacro: "step-by-step",
    instruction: "Respond using numbered steps.",
    mvpCandidate: "Yes",
  },
  concise: {
    key: "concise",
    displayName: "Concise",
    category: "Formatting",
    communityMacro: "no fluff",
    instruction: "Keep the response short and high signal.",
    mvpCandidate: "Yes",
  },
  ultimate_summary: {
    key: "ultimate_summary",
    displayName: "Ultimate summary",
    category: "Communication",
    communityMacro: "executive mode",
    instruction: "Prioritize strategic clarity and concise business language.",
    mvpCandidate: "Yes",
  },
  show_risks: {
    key: "show_risks",
    displayName: "Show risks",
    category: "Reasoning",
    communityMacro: "red team",
    instruction: "Identify risks, vulnerabilities, and failure points.",
    mvpCandidate: "Yes",
  },
  audit_mode: {
    key: "audit_mode",
    displayName: "Audit Mode",
    category: "Reasoning",
    communityMacro: "audit mode",
    instruction: "Systematically inspect for inconsistencies and gaps.",
    mvpCandidate: "Yes",
  },
  action_plan: {
    key: "action_plan",
    displayName: "Action Plan",
    category: "Workflow",
    communityMacro: "action plan",
    instruction: "Focus on actionable next steps.",
    mvpCandidate: "Yes",
  },
  fact_check: {
    key: "fact_check",
    displayName: "Fact Check",
    category: "Reasoning",
    communityMacro: "fact-check",
    instruction: "Critically verify claims and assumptions.",
    mvpCandidate: "Yes",
  },
  consult_me: {
    key: "consult_me",
    displayName: "Consult me",
    category: "Workflow",
    communityMacro: "consultant mode",
    instruction: "Use structured advisory-style communication.",
    mvpCandidate: "Yes",
  },
  thesis_mode: {
    key: "thesis_mode",
    displayName: "Thesis mode",
    category: "Workflow",
    communityMacro: "analyst mode",
    instruction: "Use evidence-heavy analytical reasoning.",
    mvpCandidate: "Yes",
  },
  json_output: {
    key: "json_output",
    displayName: "JSON Output",
    category: "Formatting",
    communityMacro: "json only",
    instruction: "Respond only in valid JSON format.",
    mvpCandidate: "Yes",
  },
  table_format: {
    key: "table_format",
    displayName: "Table Format",
    category: "Formatting",
    communityMacro: "table mode",
    instruction: "Respond using structured tables.",
    mvpCandidate: "Yes",
  },
};

export const RESPONSE_MODE_OPTIONS = Object.values(RESPONSE_MODE_MAP);
